<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Login.aspx.cs" Inherits="XkCms.WebForm.UserBox.Login" %>
<asp:literal id="ltTop" runat="server"></asp:literal>
<form id="form1" runat="server">
    <asp:panel runat="server" id="plLoginBody" cssclass="LoginDiv"><P><asp:Label id="Label1" runat="server" CssClass="left" Text="登陆名称"></asp:Label> <asp:TextBox id="txtUserName" runat="server" Width="120px" MaxLength="20"></asp:TextBox> <asp:RequiredFieldValidator id="RequiredFieldValidator1" runat="server" ControlToValidate="txtUserName" Display="Dynamic" ErrorMessage="*" SetFocusOnError="True"></asp:RequiredFieldValidator><asp:RegularExpressionValidator id="RegularExpressionValidator3" runat="server" ControlToValidate="txtUserName" ErrorMessage="*" ValidationExpression="^.{2,20}$">2到20个字符</asp:RegularExpressionValidator></P><P><asp:Label id="Label4" runat="server" CssClass="left" Text="登陆密码"></asp:Label> <asp:TextBox id="txtPass" runat="server" Width="120px" MaxLength="20" TextMode="Password"></asp:TextBox> <asp:RequiredFieldValidator id="RequiredFieldValidator4" runat="server" ControlToValidate="txtPass" Display="Dynamic" ErrorMessage="*" SetFocusOnError="True"></asp:RequiredFieldValidator><asp:RegularExpressionValidator id="RegularExpressionValidator1" runat="server" ControlToValidate="txtPass" ErrorMessage="*" ValidationExpression="^.{6,20}$">6到20个字符</asp:RegularExpressionValidator></P><P><asp:Label id="Label7" runat="server" CssClass="left" Text="验证码"></asp:Label> <asp:TextBox id="txtCheckCode" runat="server" Width="76px" AutoCompleteType="Disabled"></asp:TextBox><IMG id="ValidateCode" src="../ValidateImg.aspx" align=absMiddle /><asp:RequiredFieldValidator id="RequiredFieldValidator6" runat="server" ControlToValidate="txtCheckCode" Display="Dynamic" ErrorMessage="*" SetFocusOnError="True"></asp:RequiredFieldValidator></P><P class="foot"><asp:Button id="btnLogin" runat="server" Text="登 陆" OnClick="btnLogin_Click"></asp:Button>&nbsp; <INPUT onclick="window.location.href='Register.aspx'" type=button value="注 册" /></P></asp:panel>
    <asp:panel runat="server" id="plLoginSuccess"><asp:Literal id="ltLoginSuccess" runat="server"></asp:Literal></asp:panel>
    <asp:panel runat="server" id="plErrorMsg"><asp:Literal id="ltErrorMsg" runat="server"></asp:Literal></asp:panel>
    <asp:Literal id="ltTempErrMsg" runat="server"></asp:Literal>
</form>
<asp:literal id="ltBottom" runat="server"></asp:literal>
